apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: output
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/{{ .TagName }}/output_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./output"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/{{ .TagName }}/output_linux_arm64.tar.gz" .TagName }}
    files:
    - from: "./output"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/{{ .TagName }}/output_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./output"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/{{ .TagName }}/output_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: "./output"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/{{ .TagName }}/output_windows_amd64.zip" .TagName }}
    files:
    - from: "/output.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output.exe"
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/{{ .TagName }}/output_windows_arm64.zip" .TagName }}
    files:
    - from: "/output.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output.exe"
  shortDescription: Set custom output format for resources/namespaces
  homepage: https://github.com/GrigoriyMikhalkin/kubectl-output
  description: |
    This plugin allows you to set custom outputs for specific resources/namespaces.
    Supports both custom-column and custom-column-file formats for templates.
    When running get command serves as a wrapper for kubectl command.
