apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: output
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/v0.1.0/output_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./output"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/v0.1.0/output_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./output"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/GrigoriyMikhalkin/kubectl-output/releases/download/v0.1.0/output_windows_amd64.zip
    sha256: ""
    files:
    - from: "/output.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "output.exe"
  shortDescription: A new plugin
  homepage: https://github.com/GrigoriyMikhalkin/kubectl-output
  caveats: |
    Usage:
      $ kubectl output

    For additional options:
      $ kubectl output --help
      or https://github.com/GrigoriyMikhalkin/kubectl-output/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
